// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6fkLQgSYGuOSG6qcGaD6kdOZLLbmBCSE',
    appId: '1:1043503614722:web:c9c23634cdcc34116b501b',
    messagingSenderId: '1043503614722',
    projectId: 'excp-project',
    authDomain: 'excp-project.firebaseapp.com',
    storageBucket: 'excp-project.firebasestorage.app',
    measurementId: 'G-WGVSCPY0B8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYZZVLOp3jbksZbY72wpyCbhNqMCKzsT8',
    appId: '1:1043503614722:android:4dcd6ebd828ed0206b501b',
    messagingSenderId: '1043503614722',
    projectId: 'excp-project',
    storageBucket: 'excp-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACHnqpSiGWhTIfCVn7i7GfB_YQC2Y1OAk',
    appId: '1:1043503614722:ios:8a2e805430a177b96b501b',
    messagingSenderId: '1043503614722',
    projectId: 'excp-project',
    storageBucket: 'excp-project.firebasestorage.app',
    iosBundleId: 'com.example.excpTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACHnqpSiGWhTIfCVn7i7GfB_YQC2Y1OAk',
    appId: '1:1043503614722:ios:8a2e805430a177b96b501b',
    messagingSenderId: '1043503614722',
    projectId: 'excp-project',
    storageBucket: 'excp-project.firebasestorage.app',
    iosBundleId: 'com.example.excpTraining',
  );
}
